"""Rocket Stock Scanner - Ticker Universe

Re-exports from universe_builder.py and provides missing helpers.
All ticker lists and enrichment logic are in universe_builder.py.
"""

from __future__ import annotations

import json
from pathlib import Path

from .universe_builder import (
    get_universe,
    get_all_universes,
    get_all_tickers,
    get_universe_count,
    get_total_count,
    get_region_count,
)
from . import universe_regions

# ---------------------------------------------------------------------------
# Missing constants — universe_builder does not export these
# ---------------------------------------------------------------------------

REGIONS: dict[str, list[str]] = {
    # Lists are generated by universe_builder (see `universe.build_lists`); the
    # editor keeps the KEYS (a region key present here but not in builder is a
    # product gap, surfaced by I4 when a real cache is present).
    key: [] for key in universe_regions.REGION_META
}

REGION_DEFAULTS: dict[str, dict] = {
    key: {
        "exchange": meta["exchange"],
        "timezone": meta["timezone"],
    }
    for key, meta in universe_regions.REGION_META.items()
}

REGION_LABELS: dict[str, str] = {
    key: meta["label"]
    for key, meta in universe_regions.REGION_META.items()
}


def validate_region_maps(region_keys: list[str]) -> list[str]:
    """I4: every cache/region key must exist in all three region maps.

    Returns the list of missing keys (empty = all present). Callers use this at
    build/regen time to guarantee a region key in the cache is never invisible
    on the site (no REGION_LABELS) nor missing fetch defaults.
    """
    missing: list[str] = []
    for key in region_keys:
        if key not in REGIONS:
            missing.append(f"{key}:REGIONS")
        if key not in REGION_DEFAULTS:
            missing.append(f"{key}:REGION_DEFAULTS")
        if key not in REGION_LABELS:
            missing.append(f"{key}:REGION_LABELS")
    return missing

# ---------------------------------------------------------------------------
# Helper functions — callers expect these from universe module
# ---------------------------------------------------------------------------

def get_sector(ticker: str) -> str:
    """Get sector for a ticker. Returns empty string if not found."""
    enriched = _load_enrichment_data()
    info = enriched.get(ticker, {})
    return info.get("sector", "")


def get_region(ticker: str) -> str:
    """Get region for a ticker. Returns 'usa' by default."""
    enriched = _load_enrichment_data()
    info = enriched.get(ticker, {})
    return info.get("region", "usa")


def get_ticker_info(ticker: str) -> dict:
    """Get info dict for a ticker."""
    enriched = _load_enrichment_data()
    info = enriched.get(ticker, {})
    return {
        "ticker": ticker,
        "name": info.get("name", ""),
        "region": info.get("region", "usa"),
        "sector": info.get("sector", ""),
        "market_cap": info.get("market_cap", 0.0),
        "avg_volume": info.get("avg_volume", 0.0),
    }


def enrich_ticker_info(ticker: str, info: dict) -> dict:
    """Enrich ticker info with exchange data."""
    region = info.get("region", "usa")
    info["exchange"] = REGION_DEFAULTS.get(region, {}).get("exchange", "Unknown")
    return info


def load_enrichment_data() -> dict:
    """Load enrichment data from universe_enriched.json."""
    return _load_enrichment_data()


def _load_enrichment_data() -> dict:
    """Internal load of enrichment data."""
    enriched_path = Path(__file__).parent / "universe_enriched.json"
    if enriched_path.exists():
        with open(enriched_path, "r") as f:
            return json.load(f)
    return {}


def save_enrichment_data(data: dict) -> None:
    """Save enrichment data to universe_enriched.json."""
    enriched_path = Path(__file__).parent / "universe_enriched.json"
    with open(enriched_path, "w") as f:
        json.dump(data, f, indent=2)


def load_universe_list() -> dict[str, list[str]]:
    """Load universe list from cache."""
    return get_universe()


def save_universe_list(data: dict[str, list[str]]) -> None:
    """Save universe list to cache."""
    pass


def update_universe() -> dict[str, list[str]]:
    """Trigger universe update (alias for get_universe)."""
    return get_universe()


__all__ = [
    "get_universe",
    "get_all_universes",
    "get_all_tickers",
    "get_universe_count",
    "get_total_count",
    "get_region_count",
    "get_sector",
    "get_region",
    "get_ticker_info",
    "enrich_ticker_info",
    "REGIONS",
    "REGION_DEFAULTS",
    "REGION_LABELS",
    "load_enrichment_data",
    "save_enrichment_data",
    "load_universe_list",
    "save_universe_list",
    "update_universe",
]
